// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

//! REST adapter: router assembly and cross-cutting middleware.
//!
//! Each endpoint module builds its own [`OpenApiRouter`], and [`build_router`] merges them, splits the result
//! into an Axum router plus the generated OpenAPI document, and wraps the router in the middleware defined
//! here.
//!
//! The middleware applies two per-request input-validation bounds — a maximum body size (413) and the
//! per-request deadline (504).

pub mod health;
pub mod openapi;

use crate::config::RestServerConfig;
use crate::error::{ErrorEnvelope, ErrorKind, GatewayError, panic_message};
use crate::lifecycle::Readiness;
use crate::observability;
use axum::Router;
use axum::body::{Body, Bytes};
use axum::extract::{DefaultBodyLimit, MatchedPath, Request};
use axum::http::{HeaderMap, HeaderValue, Method, StatusCode, Uri, header};
use axum::middleware::{self, Next};
use axum::response::{IntoResponse, Response};
use futures_util::FutureExt;
use serde::Serialize;
use serde::de::DeserializeOwned;
use std::net::SocketAddr;
use std::panic::AssertUnwindSafe;
use std::sync::{Arc, OnceLock};
use std::time::{Duration, Instant};
use utoipa_axum::router::OpenApiRouter;

/// The deadline handed to a request whose configured timeout cannot be added to the current instant.
///
/// Only reachable if a duration slips past configuration validation; one hour keeps such a request bounded.
const MAX_REQUEST_DEADLINE: Duration = Duration::from_secs(3600);

/// Reserved between a request's deadline and the middleware timeout that backstops it, so a
/// response completing at the deadline still gets out instead of racing the timeout. The timeout
/// keeps the configured value; the deadline ends this much earlier.
const RESPONSE_GRACE: Duration = Duration::from_secs(1);

/// Shared state for REST handlers.
///
/// Everything here is either immutable configuration or a shared process service. Nothing is scoped to a
/// request, a session, or a client.
#[derive(Clone)]
pub struct RestState {
    pub readiness: Arc<Readiness>,
    pub bind_address: SocketAddr,
    pub started_at: Instant,
    /// The OpenAPI document generated from the router this state was installed into.
    ///
    /// [`build_router`] fills it once, after the route modules are merged and split, so the served document is
    /// exactly the contract of the routes that are actually mounted.
    pub openapi: Arc<OnceLock<serde_json::Value>>,
}

/// Per-request identifier, generated by the outermost middleware and echoed in the `x-request-id` response header and
/// error envelopes.
#[derive(Clone, Debug)]
pub struct RequestId(Arc<str>);

impl RequestId {
    /// The value echoed in the `x-request-id` header, or `unknown` when no middleware assigned one.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl Default for RequestId {
    fn default() -> Self {
        Self(Arc::from("unknown"))
    }
}

/// Absolute request deadline assigned by the same middleware that enforces it.
#[derive(Clone, Copy, Debug)]
pub struct RequestDeadline(Instant);

impl RequestDeadline {
    pub fn instant(self) -> Instant {
        self.0
    }
}

/// Middleware limits, extracted from `[server.rest]`.
#[derive(Debug, Clone)]
pub struct RestOptions {
    pub request_timeout: Duration,
    pub max_body_bytes: u64,
}

impl From<&RestServerConfig> for RestOptions {
    fn from(config: &RestServerConfig) -> Self {
        Self {
            request_timeout: config.request_timeout.get(),
            max_body_bytes: config.max_body_bytes.bytes(),
        }
    }
}

/// Marks a response whose body is already in its final shape so the error-normalising middleware leaves it alone.
#[derive(Clone, Copy)]
struct ShapedResponse;

/// Renders the error envelope with the status its kind maps to, marks the response as already shaped, and adds
/// `Retry-After` where the taxonomy calls for it.
pub fn error_response(error: &GatewayError, request_id: &RequestId) -> Response {
    let status = StatusCode::from_u16(error.kind().http_status())
        .unwrap_or(StatusCode::INTERNAL_SERVER_ERROR);
    let mut response =
        json_response_with_status(status, &ErrorEnvelope::new(error, request_id.as_str()))
            .unwrap_or_else(|_| StatusCode::INTERNAL_SERVER_ERROR.into_response());
    response.extensions_mut().insert(ShapedResponse);
    if error.kind().retry_after() {
        response
            .headers_mut()
            .insert(header::RETRY_AFTER, HeaderValue::from_static("1"));
    }
    response
}

/// Serializes `value` as a 200 JSON response. Fails only when serialization fails, which is reported as internal.
pub fn json_response<T: Serialize>(value: &T) -> Result<Response, GatewayError> {
    json_response_with_status(StatusCode::OK, value)
}

/// Serializes `value` as a JSON response with the given status. Serialization failures are reported as internal.
pub(crate) fn json_response_with_status<T: Serialize>(
    status: StatusCode,
    value: &T,
) -> Result<Response, GatewayError> {
    let body = serde_json::to_vec(value).map_err(|error| {
        GatewayError::internal(format!("failed to serialize JSON response: {error}"))
    })?;
    let mut response = (status, Body::from(body)).into_response();
    response.headers_mut().insert(
        header::CONTENT_TYPE,
        HeaderValue::from_static("application/json"),
    );
    Ok(response)
}

/// Deserializes a JSON request body, requiring a JSON `Content-Type`.
pub fn parse_json_body<T: DeserializeOwned>(
    headers: &HeaderMap,
    body: &Bytes,
) -> Result<T, GatewayError> {
    validate_json_content_type(headers)?;
    serde_json::from_slice(body)
        .map_err(|error| GatewayError::invalid_argument(format!("invalid JSON body: {error}")))
}

pub(crate) fn validate_json_content_type(headers: &HeaderMap) -> Result<(), GatewayError> {
    let Some(value) = headers.get(header::CONTENT_TYPE) else {
        return Err(GatewayError::new(
            crate::error::ErrorKind::UnsupportedMediaType,
            "Content-Type must be application/json or application/*+json",
        ));
    };
    let media_type = value
        .to_str()
        .map_err(|_| GatewayError::invalid_argument("unreadable Content-Type header"))?
        .split(';')
        .next()
        .unwrap_or_default()
        .trim()
        .to_ascii_lowercase();
    let supported = media_type == "application/json"
        || media_type
            .strip_prefix("application/")
            .is_some_and(|subtype| subtype.ends_with("+json"));
    if supported {
        Ok(())
    } else {
        Err(GatewayError::new(
            crate::error::ErrorKind::UnsupportedMediaType,
            "Content-Type must be application/json or application/*+json",
        ))
    }
}

/// Rejects any query string on endpoints that define no query parameters.
pub fn ensure_no_query(uri: &Uri) -> Result<(), GatewayError> {
    if uri.query().is_some() {
        return Err(GatewayError::invalid_argument(
            "this operation does not accept query parameters",
        ));
    }
    Ok(())
}

/// Marks a response as final so the error-normalising middleware does not rewrite its body. Use it for handler
/// responses that already carry their own envelope.
pub fn shaped(mut response: Response) -> Response {
    response.extensions_mut().insert(ShapedResponse);
    response
}

/// Assembles the REST frontend from the REST configuration and the shared process services.
///
/// This is the frontend's entry point for the lifecycle: it owns how the handler state is built and
/// the router is wired, so the lifecycle stays protocol-agnostic and only supervises the listener
/// this router is served on. `local_addr` is the resolved bound address, which differs from the
/// configured one when the port is 0.
pub fn build(
    rest_config: &RestServerConfig,
    readiness: &Arc<Readiness>,
    local_addr: SocketAddr,
) -> Router {
    let state = RestState {
        readiness: readiness.clone(),
        bind_address: local_addr,
        started_at: Instant::now(),
        openapi: Arc::new(OnceLock::new()),
    };
    build_router(state, &RestOptions::from(rest_config))
}

/// Builds the P1 router: the health routes (`GET /health` for liveness, `GET /ready` for
/// readiness) sit outside both the acceptance guard and the body/deadline budget so they answer
/// while draining and never carry a body; every guarded route (today `/v1/openapi.json`, later all
/// data/control routes) carries the request-body size and deadline budget, with the acceptance
/// guard outermost so draining answers 503 without consuming bodies.
pub fn build_router(state: RestState, options: &RestOptions) -> Router {
    let (guarded_router, guarded_api) = OpenApiRouter::new()
        .merge(openapi::routes())
        .split_for_parts();
    let (open_router, open_api) = OpenApiRouter::new()
        .merge(health::routes())
        .split_for_parts();

    let mut api = guarded_api;
    api.merge(open_api);
    let _ = state.openapi.set(openapi::finalize(api));

    // `apply_data_limits` also stamps the request deadline, so the guarded side needs no separate
    // `assign_request_deadline` layer.
    let guarded = apply_data_limits(guarded_router.with_state(state.clone()), options);
    let guarded = apply_acceptance_guard(guarded, state.readiness.clone());
    let open = open_router
        .fallback(unknown_route)
        .with_state(state)
        .layer(middleware::from_fn(assign_request_deadline(
            options.request_timeout,
        )));
    apply_common_middleware(open.merge(guarded))
}

/// Rejects new application work after graceful draining starts while keeping `GET /health` available.
fn apply_acceptance_guard(router: Router, readiness: Arc<Readiness>) -> Router {
    router.layer(middleware::from_fn(move |request: Request, next: Next| {
        let readiness = readiness.clone();
        async move {
            if let Err(error) = readiness.ensure_accepting() {
                let request_id = request
                    .extensions()
                    .get::<RequestId>()
                    .cloned()
                    .unwrap_or_default();
                return error_response(&error, &request_id);
            }
            next.run(request).await
        }
    }))
}

/// Applies the cross-cutting middleware stack to an already-routed app.
///
/// Exposed separately so tests can wrap purpose-built routers with the production middleware.
/// The body-limit layer is a streaming-body backstop. Requests with a declared length are rejected earlier with an
/// envelope.
///
/// Order (outermost first): request-id assignment and error normalisation, then access logging, then the
/// body size and deadline limits.
pub fn apply_middleware(router: Router, options: &RestOptions) -> Router {
    apply_common_middleware(apply_data_limits(router, options))
}

/// The deadline of a request starting now, ending [`RESPONSE_GRACE`] before the middleware timeout.
///
/// The checked additions are defence in depth — configuration caps every duration well below the
/// instant-arithmetic limit — and, like Envoy's `grpc_timeout_offset`, the grace applies only when
/// the timeout is longer than it.
fn deadline_from_now(request_timeout: Duration) -> RequestDeadline {
    let handler_budget = if request_timeout > RESPONSE_GRACE {
        request_timeout - RESPONSE_GRACE
    } else {
        request_timeout
    };
    let now = Instant::now();
    RequestDeadline(
        now.checked_add(handler_budget)
            .or_else(|| now.checked_add(MAX_REQUEST_DEADLINE))
            .unwrap_or(now),
    )
}

/// Records the absolute deadline of a request that does not pass through the data-limit layer.
fn assign_request_deadline(
    request_timeout: Duration,
) -> impl Fn(Request, Next) -> std::pin::Pin<Box<dyn Future<Output = Response> + Send>> + Clone {
    move |mut request: Request, next: Next| {
        Box::pin(async move {
            request
                .extensions_mut()
                .insert(deadline_from_now(request_timeout));
            next.run(request).await
        })
    }
}

fn apply_data_limits(router: Router, options: &RestOptions) -> Router {
    let request_timeout = options.request_timeout;
    let max_body_bytes = options.max_body_bytes;

    let limits = move |mut request: Request, next: Next| async move {
        let request_id = request
            .extensions()
            .get::<RequestId>()
            .cloned()
            .unwrap_or_default();
        request
            .extensions_mut()
            .insert(deadline_from_now(request_timeout));

        let oversized = declared_content_length(&request).filter(|length| *length > max_body_bytes);
        if let Some(length) = oversized {
            log::warn!(
                "request_id={} rejecting body of {} bytes above {} bytes",
                request_id.as_str(),
                length,
                max_body_bytes
            );
            return error_response(
                &GatewayError::limit_exceeded(format!(
                    "request body of {length} bytes exceeds the limit of {max_body_bytes} bytes"
                )),
                &request_id,
            );
        }

        // Rejections are not counted separately: they leave through the access-log layer above, which
        // records them in `fluss_gateway_rest_requests_total` under their status code.
        let result = tokio::time::timeout(request_timeout, next.run(request)).await;
        match result {
            Ok(response) => response,
            Err(_) => {
                log::warn!(
                    "request_id={} deadline exceeded after {:?}",
                    request_id.as_str(),
                    request_timeout
                );
                error_response(
                    &GatewayError::deadline_exceeded("request deadline exceeded"),
                    &request_id,
                )
            }
        }
    };

    router
        .layer(DefaultBodyLimit::max(
            usize::try_from(max_body_bytes).unwrap_or(usize::MAX),
        ))
        .layer(middleware::from_fn(limits))
}

fn apply_common_middleware(router: Router) -> Router {
    router
        .layer(middleware::from_fn(catch_panic))
        .layer(middleware::from_fn(request_log))
        .layer(middleware::from_fn(request_context))
}

/// Turns a panic below this layer into the error envelope a client is promised.
///
/// Sitting inside the access-log layer, the synthesised 500 is logged and counted like any other
/// response, where a dropped connection would have been recorded nowhere. The payload goes to the
/// log, never into the response, since it can carry internal detail.
async fn catch_panic(request: Request, next: Next) -> Response {
    let request_id = request
        .extensions()
        .get::<RequestId>()
        .cloned()
        .unwrap_or_default();
    match AssertUnwindSafe(next.run(request)).catch_unwind().await {
        Ok(response) => response,
        Err(payload) => {
            log::error!(
                "request_id={} handler panicked: {}",
                request_id.as_str(),
                panic_message(payload)
            );
            error_response(&GatewayError::internal("internal error"), &request_id)
        }
    }
}

async fn request_log(request: Request, next: Next) -> Response {
    let started = Instant::now();
    let method = request.method().clone();
    let route = request
        .extensions()
        .get::<MatchedPath>()
        .map(MatchedPath::as_str)
        .unwrap_or("<unmatched>")
        .to_string();
    let request_id = request
        .extensions()
        .get::<RequestId>()
        .cloned()
        .unwrap_or_default();
    let response = next.run(request).await;
    let elapsed = started.elapsed();
    let status = response.status();
    // No route carries a `{cluster}` segment, so every request gets the static `none` label;
    // caller-supplied values never become label values.
    observability::http_request("none", method.as_str(), &route, status.as_u16(), elapsed);
    log::info!(
        "{}",
        format_request_log(&method, &route, &request_id, status, elapsed.as_millis())
    );
    response
}

fn format_request_log(
    method: &Method,
    route: &str,
    request_id: &RequestId,
    status: StatusCode,
    elapsed_ms: u128,
) -> String {
    format!(
        "method={method} route={route} request_id={} status={} elapsed_ms={elapsed_ms}",
        request_id.as_str(),
        status.as_u16()
    )
}

async fn request_context(mut request: Request, next: Next) -> Response {
    let request_id = RequestId(Arc::from(uuid::Uuid::new_v4().to_string()));
    request.extensions_mut().insert(request_id.clone());

    let response = next.run(request).await;
    let mut response = normalize_error(response, &request_id);

    if let Ok(value) = HeaderValue::from_str(request_id.as_str()) {
        response.headers_mut().insert("x-request-id", value);
    }
    response
}

/// Classifies a status the framework produced on its own — a rejected extractor, a route that exists for
/// another method — so it can be answered with the same envelope as a handler failure.
fn framework_error_kind(status: StatusCode) -> ErrorKind {
    match status.as_u16() {
        400 | 422 => ErrorKind::InvalidArgument,
        404 => ErrorKind::NotFound,
        405 => ErrorKind::MethodNotAllowed,
        406 => ErrorKind::NotAcceptable,
        408 | 504 => ErrorKind::DeadlineExceeded,
        413 => ErrorKind::LimitExceeded,
        415 => ErrorKind::UnsupportedMediaType,
        429 => ErrorKind::ResourceExhausted,
        501 => ErrorKind::Unsupported,
        503 => ErrorKind::Unavailable,
        server_error if server_error >= 500 => ErrorKind::Internal,
        _ => ErrorKind::InvalidArgument,
    }
}

/// The reason phrase of the status a kind maps to, so this layer keeps no message table of its own.
fn framework_error_message(kind: ErrorKind) -> &'static str {
    StatusCode::from_u16(kind.http_status())
        .ok()
        .and_then(|status| status.canonical_reason())
        .unwrap_or("request failed")
}

fn normalize_error(response: Response, request_id: &RequestId) -> Response {
    let status = response.status();
    if !(status.is_client_error() || status.is_server_error()) {
        return response;
    }
    if response.extensions().get::<ShapedResponse>().is_some() {
        return response;
    }

    let kind = framework_error_kind(status);
    error_response(
        &GatewayError::new(kind, framework_error_message(kind)),
        request_id,
    )
}

async fn unknown_route(method: Method, uri: Uri, request: Request) -> Response {
    let request_id = request
        .extensions()
        .get::<RequestId>()
        .cloned()
        .unwrap_or_default();
    error_response(
        &GatewayError::not_found(format!("no route for {method} {}", uri.path())),
        &request_id,
    )
}

fn declared_content_length(request: &Request) -> Option<u64> {
    request
        .headers()
        .get(header::CONTENT_LENGTH)
        .and_then(|value| value.to_str().ok())
        .and_then(|value| value.parse().ok())
}

#[cfg(test)]
pub mod test_support {
    //! Router and state builders shared by the in-crate protocol tests.

    use super::*;

    /// Middleware options with short, test-friendly bounds.
    pub fn test_options() -> RestOptions {
        RestOptions {
            request_timeout: Duration::from_secs(5),
            max_body_bytes: 1024,
        }
    }

    /// Builds handler state over a fresh readiness gate, which starts neither serving nor draining.
    pub fn test_state() -> RestState {
        RestState {
            readiness: Arc::new(Readiness::new()),
            bind_address: "127.0.0.1:0".parse().expect("valid"),
            started_at: Instant::now(),
            openapi: Arc::new(OnceLock::new()),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::routing::{get, post};
    use http_body_util::BodyExt;
    use serde::Deserialize;
    use tower::ServiceExt;

    #[derive(Debug, Deserialize, PartialEq)]
    #[serde(deny_unknown_fields)]
    struct BodyFixture {
        value: u32,
    }

    async fn body_json(response: Response) -> serde_json::Value {
        let bytes = response
            .into_body()
            .collect()
            .await
            .expect("body")
            .to_bytes();
        serde_json::from_slice(&bytes).expect("json body")
    }

    #[test]
    fn shared_json_parser_enforces_media_type_and_serde_strictness() {
        let body = Bytes::from_static(br#"{"value": 7}"#);
        assert!(parse_json_body::<BodyFixture>(&HeaderMap::new(), &body).is_err());

        let mut headers = HeaderMap::new();
        headers.insert(header::CONTENT_TYPE, HeaderValue::from_static("text/plain"));
        assert!(parse_json_body::<BodyFixture>(&headers, &body).is_err());

        headers.insert(
            header::CONTENT_TYPE,
            HeaderValue::from_static("application/vnd.fluss+json; charset=utf-8"),
        );
        assert_eq!(
            parse_json_body::<BodyFixture>(&headers, &body).unwrap(),
            BodyFixture { value: 7 }
        );
        for bad in [
            br#"{"value": 7, "unknown": true}"#.as_slice(),
            br#"{"value": 7, "value": 8}"#.as_slice(),
            br#"{"value":"#.as_slice(),
        ] {
            assert!(
                parse_json_body::<BodyFixture>(&headers, &Bytes::copy_from_slice(bad)).is_err()
            );
        }
        assert!(parse_json_body::<BodyFixture>(&headers, &Bytes::new()).is_err());
    }

    #[tokio::test]
    async fn unknown_route_yields_404_envelope() {
        let app = build_router(test_support::test_state(), &test_support::test_options());
        let response = app
            .oneshot(Request::builder().uri("/nope").body(Body::empty()).unwrap())
            .await
            .unwrap();

        assert_eq!(response.status(), StatusCode::NOT_FOUND);
        let header_id = response
            .headers()
            .get("x-request-id")
            .and_then(|v| v.to_str().ok())
            .map(str::to_string)
            .expect("x-request-id header");

        let json = body_json(response).await;
        assert_eq!(json["error"]["code"], "not_found");
        assert_eq!(json["error"]["request_id"], header_id.as_str());
        assert!(
            json["error"]["message"].as_str().unwrap().contains("/nope"),
            "message names the missing route: {json}"
        );
    }

    #[tokio::test]
    async fn oversized_body_yields_413_envelope() {
        let app = apply_middleware(
            Router::new().route("/echo", post(|| async { "ok" })),
            &test_support::test_options(),
        );
        let response = app
            .oneshot(
                Request::builder()
                    .method(Method::POST)
                    .uri("/echo")
                    .header(header::CONTENT_LENGTH, "1048576")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();

        assert_eq!(response.status(), StatusCode::PAYLOAD_TOO_LARGE);
        let json = body_json(response).await;
        assert_eq!(json["error"]["code"], "limit_exceeded");
        assert!(json["error"]["request_id"].as_str().is_some());
    }

    #[tokio::test]
    async fn request_timeout_yields_504_envelope() {
        /// Runs longer than the configured test request deadline.
        async fn slow() -> &'static str {
            tokio::time::sleep(Duration::from_millis(250)).await;
            "ok"
        }
        let options = RestOptions {
            request_timeout: Duration::from_millis(50),
            max_body_bytes: 1024,
        };
        let app = apply_middleware(Router::new().route("/slow", get(slow)), &options);

        let response = app
            .oneshot(Request::builder().uri("/slow").body(Body::empty()).unwrap())
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::GATEWAY_TIMEOUT);
        let json = body_json(response).await;
        assert_eq!(json["error"]["code"], "timeout");
    }

    /// The deadline reserves the response grace, except for timeouts that are not longer than it,
    /// which keep their full budget.
    #[test]
    fn the_deadline_reserves_the_response_grace_when_the_timeout_allows_it() {
        for (timeout, budget) in [
            (
                Duration::from_secs(30),
                Duration::from_secs(30) - RESPONSE_GRACE,
            ),
            (RESPONSE_GRACE, RESPONSE_GRACE),
            (Duration::from_millis(200), Duration::from_millis(200)),
        ] {
            let before = Instant::now();
            let deadline = deadline_from_now(timeout).instant();
            let after = Instant::now();

            assert!(deadline >= before + budget, "timeout={timeout:?}");
            assert!(
                deadline <= after + budget + Duration::from_millis(50),
                "timeout={timeout:?}"
            );
        }
    }

    /// A handler that finishes exactly at its deadline still gets its response out: the middleware
    /// timeout backstops the deadline plus the response grace instead of racing it.
    #[tokio::test]
    async fn response_completing_at_the_deadline_is_delivered() {
        async fn finishes_at_deadline(request: Request) -> &'static str {
            let deadline = request
                .extensions()
                .get::<RequestDeadline>()
                .copied()
                .expect("the limits middleware assigns the deadline");
            tokio::time::sleep_until(tokio::time::Instant::from_std(deadline.instant())).await;
            "ok"
        }
        let options = RestOptions {
            request_timeout: RESPONSE_GRACE + Duration::from_millis(400),
            max_body_bytes: 1024,
        };
        let app = apply_middleware(
            Router::new().route("/deadline", get(finishes_at_deadline)),
            &options,
        );

        let response = app
            .oneshot(
                Request::builder()
                    .uri("/deadline")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::OK);
    }

    /// A route that exists for another method answers the shared envelope with a code the published
    /// vocabulary contains.
    #[tokio::test]
    async fn wrong_method_yields_a_405_envelope() {
        let app = build_router(test_support::test_state(), &test_support::test_options());
        let response = app
            .oneshot(
                Request::builder()
                    .method(Method::POST)
                    .uri("/health")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();

        assert_eq!(response.status(), StatusCode::METHOD_NOT_ALLOWED);
        let json = body_json(response).await;
        assert_eq!(json["error"]["code"], "method_not_allowed");
        assert!(
            crate::error::wire_codes().contains(&"method_not_allowed"),
            "the published vocabulary declares every code the gateway emits"
        );
    }

    #[tokio::test]
    async fn concurrent_requests_are_never_rejected_with_429() {
        /// Holds a request open long enough for several to overlap.
        async fn slow() -> &'static str {
            tokio::time::sleep(Duration::from_millis(50)).await;
            "ok"
        }
        let app = apply_middleware(
            Router::new().route("/slow", get(slow)),
            &test_support::test_options(),
        );
        let request = || Request::builder().uri("/slow").body(Body::empty()).unwrap();

        let responses =
            futures_util::future::join_all((0..16).map(|_| app.clone().oneshot(request()))).await;

        for response in responses {
            assert_eq!(response.unwrap().status(), StatusCode::OK);
        }
    }

    #[tokio::test]
    async fn success_responses_carry_request_id_header() {
        let app = build_router(test_support::test_state(), &test_support::test_options());
        let response = app
            .oneshot(
                Request::builder()
                    .uri("/health")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::OK);
        assert!(response.headers().contains_key("x-request-id"));
    }

    /// A panicking handler answers the shared envelope instead of dropping the connection.
    #[tokio::test]
    async fn a_panicking_handler_yields_a_500_envelope() {
        async fn boom() -> &'static str {
            panic!("handler bug");
        }
        let app = apply_middleware(
            Router::new().route("/boom", get(boom)),
            &test_support::test_options(),
        );

        // The default panic hook still prints the payload; that output is expected here.
        let response = app
            .oneshot(Request::builder().uri("/boom").body(Body::empty()).unwrap())
            .await
            .unwrap();

        assert_eq!(response.status(), StatusCode::INTERNAL_SERVER_ERROR);
        let request_id = response
            .headers()
            .get("x-request-id")
            .and_then(|value| value.to_str().ok())
            .map(str::to_string)
            .expect("x-request-id header");
        let json = body_json(response).await;
        assert_eq!(json["error"]["code"], "internal");
        assert_eq!(json["error"]["request_id"], request_id.as_str());
        assert!(
            !json["error"]["message"]
                .as_str()
                .unwrap()
                .contains("handler bug"),
            "the panic payload stays in the log, never in the response: {json}"
        );
    }

    #[test]
    fn request_log_contains_protocol_context() {
        let message = format_request_log(
            &Method::POST,
            "/v1/clusters/{cluster}/databases",
            &RequestId(Arc::from("request-7")),
            StatusCode::CREATED,
            23,
        );
        assert_eq!(
            message,
            "method=POST route=/v1/clusters/{cluster}/databases request_id=request-7 status=201 elapsed_ms=23"
        );
    }
}
